// i18n-audit-ignore-file -- search keywords in the source language: translating 520 of them is a
// data job of its own, tracked separately, and not something a screen can be held up for.

/**
 * What a reader can type to find an emoji.
 *
 * Kept apart from the categories so the picker itself carries no prose: the words here are matched,
 * never drawn. They are French today, which means the search only answers a French reader; every
 * other language falls back to matching the emoji itself. A language gets its own map by adding one
 * here, keyed the same way.
 */
export const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "sourire content",
  "😃": "sourire joie",
  "😄": "rire joie",
  "😁": "sourire dents",
  "😆": "rire",
  "😅": "rire sueur gene",
  "🤣": "explose rire",
  "😂": "pleure rire larmes",
  "🙂": "sourire leger",
  "🙃": "envers ironie",
  "😉": "clin oeil",
  "😊": "content timide",
  "😇": "ange innocent",
  "🥰": "amour coeurs",
  "😍": "amour yeux coeur",
  "🤩": "etoiles wow admiration",
  "😘": "bisou coeur",
  "😗": "bisou",
  "😚": "bisou ferme",
  "😙": "bisou sourire",
  "🥲": "sourire larme",
  "😋": "miam langue",
  "😛": "langue",
  "😜": "langue clin",
  "🤪": "fou dingue",
  "😝": "langue yeux fermes",
  "🤑": "argent riche",
  "🤗": "calin",
  "🤭": "gene main bouche",
  "🤫": "chut silence",
  "🤔": "reflechit pense",
  "🤐": "bouche cousue",
  "🤨": "sceptique doute",
  "😐": "neutre",
  "😑": "sans expression",
  "😶": "silence sans bouche",
  "😏": "malin sourire coin",
  "😒": "agace blase",
  "🙄": "yeux ciel agace",
  "😬": "grimace gene",
  "🤥": "menteur",
  "😌": "soulage calme",
  "😔": "deprime triste",
  "😪": "fatigue endormi",
  "🤤": "bave",
  "😴": "dort sommeil",
  "😷": "masque malade",
  "🤒": "malade thermometre",
  "🤕": "blesse bandage",
  "🤢": "nausee degout",
  "🤮": "vomi",
  "🤧": "eternue mouchoir",
  "🥵": "chaud transpire",
  "🥶": "froid gele",
  "🥴": "etourdi ivre",
  "😵": "sonne ko",
  "🤯": "cerveau explose choc",
  "🤠": "cowboy",
  "🥳": "fete anniversaire",
  "😎": "cool lunettes",
  "🤓": "geek intello",
  "🧐": "monocle observe",
  "😕": "confus",
  "😟": "inquiet",
  "🙁": "triste leger",
  "😮": "surpris bouche",
  "😯": "etonne",
  "😲": "choque",
  "😳": "rougit gene",
  "🥺": "suppliant yeux",
  "😦": "consterne",
  "😧": "angoisse",
  "😨": "peur",
  "😰": "anxieux sueur",
  "😥": "triste soulage",
  "😢": "pleure larme",
  "😭": "pleure sanglot",
  "😱": "crie peur",
  "😖": "confus souffre",
  "😣": "persevere",
  "😞": "decu",
  "😓": "sueur froide",
  "😩": "las fatigue",
  "😫": "epuise",
  "🥱": "baille ennui",
  "😤": "enerve fier",
  "😡": "colere rouge",
  "😠": "enerve fache",
  "🤬": "jure insulte",
  "😈": "diable malicieux",
  "👿": "diable colere",
  "💀": "mort crane",
  "💩": "caca",
  "🤡": "clown",
  "👻": "fantome",
  "👽": "alien extraterrestre",
  "🤖": "robot",
  "👍": "pouce bien ok oui approuve",
  "👎": "pouce bas non",
  "👌": "ok parfait",
  "🤌": "doigts italien",
  "🤏": "petit pincee",
  "✌️": "paix victoire",
  "🤞": "doigts croises chance",
  "🤟": "amour signe",
  "🤘": "rock cornes",
  "🤙": "appelle cool",
  "👈": "gauche doigt",
  "👉": "droite doigt",
  "👆": "haut doigt",
  "👇": "bas doigt",
  "☝️": "index haut",
  "✋": "main stop",
  "🤚": "main dos",
  "🖐️": "main doigts",
  "🖖": "vulcain spock",
  "👋": "salut bonjour au revoir",
  "🤝": "poignee main accord deal",
  "🙏": "merci priere stp svp",
  "✍️": "ecrit main",
  "💅": "vernis ongles",
  "👏": "applaudit bravo",
  "🙌": "mains levees hourra",
  "👐": "mains ouvertes",
  "🤲": "mains paume",
  "💪": "muscle force",
  "🦾": "bras mecanique",
  "👀": "yeux regarde",
  "👁️": "oeil",
  "🫶": "coeur mains amour",
  "🫡": "salut militaire",
  "🫢": "surprise main",
  "🧠": "cerveau reflexion",
  "👶": "bebe",
  "🧒": "enfant",
  "👦": "garcon",
  "👧": "fille",
  "🧑": "personne adulte",
  "👨": "homme",
  "👩": "femme",
  "🧓": "senior",
  "👴": "grand pere",
  "👵": "grand mere",
  "🧔": "barbe",
  "👮": "police",
  "🕵️": "detective espion",
  "👷": "ouvrier chantier",
  "👨‍💼": "employe bureau",
  "👩‍💻": "developpeuse informatique",
  "👨‍💻": "developpeur informatique",
  "👨‍🔧": "mecanicien",
  "👩‍🍳": "cuisiniere chef",
  "👨‍🏫": "professeur enseignant",
  "🧑‍🚀": "astronaute",
  "🦸": "super heros",
  "🦹": "super vilain",
  "🧑‍🎨": "artiste peintre",
  "🤵": "costume marie",
  "👰": "mariee",
  "🎅": "pere noel",
  "🧑‍🎄": "noel",
  "🦺": "gilet securite",
  "🏃": "court course",
  "🚶": "marche pieton",
  "💃": "danse femme",
  "🕺": "danse homme",
  "❤️": "coeur rouge amour",
  "🧡": "coeur orange",
  "💛": "coeur jaune",
  "💚": "coeur vert",
  "💙": "coeur bleu",
  "💜": "coeur violet",
  "🖤": "coeur noir",
  "🤍": "coeur blanc",
  "🤎": "coeur marron",
  "💔": "coeur brise chagrin",
  "❣️": "coeur exclamation",
  "💕": "deux coeurs",
  "💞": "coeurs tournent",
  "💓": "coeur bat",
  "💗": "coeur grandit",
  "💖": "coeur brille",
  "💘": "coeur fleche",
  "💝": "coeur cadeau",
  "💟": "coeur deco",
  "❤️‍🔥": "coeur feu passion",
  "❤️‍🩹": "coeur repare",
  "💯": "cent parfait top",
  "💋": "bisou levres",
  "💌": "lettre amour",
  "🐶": "chien",
  "🐱": "chat",
  "🐭": "souris",
  "🐹": "hamster",
  "🐰": "lapin",
  "🦊": "renard",
  "🐻": "ours",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tigre",
  "🦁": "lion",
  "🐮": "vache",
  "🐷": "cochon",
  "🐸": "grenouille",
  "🐵": "singe",
  "🐔": "poule",
  "🐧": "pingouin",
  "🐦": "oiseau",
  "🦆": "canard",
  "🦉": "hibou",
  "🐴": "cheval",
  "🦄": "licorne",
  "🐝": "abeille",
  "🐛": "chenille",
  "🦋": "papillon",
  "🐌": "escargot",
  "🐞": "coccinelle",
  "🐢": "tortue",
  "🐍": "serpent",
  "🐙": "poulpe",
  "🦑": "calmar",
  "🦀": "crabe",
  "🐬": "dauphin",
  "🐳": "baleine",
  "🐟": "poisson",
  "🦈": "requin",
  "🐊": "crocodile",
  "🐘": "elephant",
  "🦒": "girafe",
  "🐐": "chevre",
  "🌵": "cactus",
  "🌲": "sapin arbre",
  "🌳": "arbre",
  "🌴": "palmier",
  "🌿": "plante feuille",
  "☘️": "trefle",
  "🍀": "trefle chance",
  "🍁": "erable automne",
  "🍂": "feuilles automne",
  "🌸": "fleur cerisier",
  "🌷": "tulipe",
  "🌹": "rose",
  "🌻": "tournesol soleil",
  "🌼": "marguerite",
  "🌈": "arc en ciel",
  "⭐": "etoile favori",
  "🌟": "etoile brille",
  "✨": "etincelles magie",
  "🔥": "feu flamme chaud top",
  "💧": "goutte eau",
  "🌊": "vague mer",
  "⚡": "eclair energie rapide",
  "☀️": "soleil beau temps",
  "⛅": "nuage soleil",
  "☁️": "nuage",
  "🌙": "lune nuit",
  "❄️": "neige flocon froid",
  "🍏": "pomme verte",
  "🍎": "pomme fruit",
  "🍐": "poire",
  "🍊": "orange",
  "🍋": "citron",
  "🍌": "banane",
  "🍉": "pasteque",
  "🍇": "raisin",
  "🍓": "fraise",
  "🫐": "myrtille",
  "🍒": "cerise",
  "🍑": "peche",
  "🥭": "mangue",
  "🍍": "ananas",
  "🥥": "noix coco",
  "🥝": "kiwi",
  "🍅": "tomate",
  "🥑": "avocat",
  "🥕": "carotte",
  "🌽": "mais",
  "🥔": "pomme terre",
  "🍞": "pain",
  "🥐": "croissant",
  "🥖": "baguette",
  "🧀": "fromage",
  "🥚": "oeuf",
  "🍳": "oeuf plat",
  "🥓": "bacon lard",
  "🍔": "burger hamburger",
  "🍟": "frites",
  "🍕": "pizza",
  "🌭": "hot dog",
  "🥪": "sandwich",
  "🌮": "taco",
  "🌯": "burrito",
  "🥗": "salade",
  "🍝": "pates",
  "🍜": "nouilles ramen",
  "🍣": "sushi",
  "🍤": "crevette",
  "🍚": "riz",
  "🍦": "glace",
  "🍩": "donut beignet",
  "🍪": "cookie biscuit",
  "🎂": "gateau anniversaire",
  "🍰": "part gateau",
  "🧁": "cupcake",
  "🍫": "chocolat",
  "🍬": "bonbon",
  "🍿": "popcorn",
  "☕": "cafe the",
  "🍵": "the vert",
  "🧃": "jus brique",
  "🥤": "soda gobelet",
  "🍺": "biere trinque",
  "🍻": "bieres sante",
  "🍷": "vin verre",
  "🥂": "champagne trinque",
  "🍾": "champagne bouteille",
  "🍸": "cocktail",
  "🚗": "voiture",
  "🚕": "taxi",
  "🚙": "suv",
  "🚌": "bus",
  "🚎": "trolley",
  "🏎️": "course voiture",
  "🚓": "police voiture",
  "🚑": "ambulance",
  "🚒": "pompier camion",
  "🚚": "camion",
  "🚜": "tracteur",
  "🛵": "scooter",
  "🏍️": "moto",
  "🚲": "velo",
  "🛴": "trottinette",
  "🚂": "train locomotive",
  "🚆": "train",
  "🚊": "tram",
  "🚉": "gare",
  "✈️": "avion vol",
  "🛫": "decollage",
  "🛬": "atterrissage",
  "🚀": "fusee lance rapide",
  "🛸": "ovni soucoupe",
  "🚁": "helicoptere",
  "⛵": "voilier bateau",
  "🚤": "hors bord",
  "🛳️": "paquebot",
  "⚓": "ancre",
  "⛽": "essence station",
  "🚦": "feu circulation",
  "🗺️": "carte",
  "🗼": "tour",
  "🏰": "chateau",
  "🗽": "liberte statue",
  "🏝️": "ile plage",
  "🏔️": "montagne",
  "🏕️": "camping",
  "🏠": "maison",
  "🏢": "immeuble bureau",
  "🏭": "usine",
  "⚽": "foot ballon",
  "🏀": "basket",
  "🏈": "foot americain",
  "⚾": "baseball",
  "🎾": "tennis",
  "🏐": "volley",
  "🏉": "rugby",
  "🎱": "billard",
  "🏓": "ping pong",
  "🏸": "badminton",
  "🥅": "but cage",
  "⛳": "golf",
  "🏹": "tir arc",
  "🎣": "peche",
  "🥊": "boxe",
  "🥋": "judo karate",
  "⛷️": "ski",
  "🏂": "snowboard",
  "🏋️": "musculation",
  "🤸": "gym roue",
  "🤾": "handball",
  "🏊": "natation",
  "🚴": "cyclisme velo",
  "🧗": "escalade",
  "🏆": "trophee gagne victoire",
  "🥇": "or premier medaille",
  "🥈": "argent second",
  "🥉": "bronze troisieme",
  "🏅": "medaille",
  "🎯": "cible objectif",
  "🎮": "jeu manette",
  "🕹️": "joystick arcade",
  "🎲": "des hasard",
  "♟️": "echecs pion",
  "🎸": "guitare musique",
  "🎹": "piano clavier",
  "🥁": "batterie tambour",
  "🎺": "trompette",
  "🎧": "casque musique",
  "🎤": "micro chant",
  "🎨": "peinture art",
  "🎬": "cinema clap",
  "🎉": "fete cotillon bravo",
  "🎊": "confettis fete",
  "🎈": "ballon fete",
  "🎁": "cadeau",
  "🎆": "feu artifice",
  "💡": "idee ampoule",
  "🔦": "lampe torche",
  "🔋": "batterie",
  "🔌": "prise electrique",
  "💻": "ordinateur laptop",
  "🖥️": "ecran ordinateur",
  "⌨️": "clavier",
  "🖱️": "souris",
  "🖨️": "imprimante",
  "📱": "telephone mobile",
  "☎️": "telephone fixe",
  "📞": "combine appel",
  "📟": "bipeur",
  "📠": "fax",
  "📷": "appareil photo",
  "📹": "camera video",
  "🎥": "camera cinema",
  "📺": "television",
  "📻": "radio",
  "⏰": "reveil alarme",
  "⏱️": "chronometre",
  "⌚": "montre",
  "📡": "antenne satellite",
  "🔍": "loupe recherche",
  "🔒": "cadenas prive verrou",
  "🔓": "cadenas ouvert",
  "🔑": "cle acces",
  "🗝️": "cle ancienne",
  "🔨": "marteau",
  "🛠️": "outils",
  "⚙️": "engrenage reglage",
  "🧰": "boite outils",
  "🧲": "aimant",
  "💰": "argent sac",
  "💳": "carte bancaire",
  "💵": "billet dollar",
  "🪙": "piece monnaie",
  "📦": "colis boite",
  "📩": "enveloppe message",
  "📨": "courrier recu",
  "✉️": "enveloppe mail",
  "📎": "trombone piece jointe",
  "📌": "epingle punaise important",
  "📍": "position lieu",
  "📅": "calendrier date",
  "📆": "calendrier",
  "📊": "graphique barres stats",
  "📈": "hausse graphique",
  "📉": "baisse graphique",
  "📋": "presse papier liste",
  "📁": "dossier fichier",
  "📂": "dossier ouvert",
  "🗂️": "classeur onglets",
  "📝": "note ecrire",
  "✏️": "crayon modifier",
  "🖊️": "stylo",
  "📚": "livres",
  "📖": "livre ouvert",
  "🔖": "marque page signet",
  "💊": "medicament pilule",
  "🧪": "eprouvette chimie",
  "🔬": "microscope",
  "🧬": "adn genetique",
  "🩺": "stethoscope sante",
  "✅": "coche valide fait ok oui",
  "☑️": "case cochee",
  "✔️": "coche",
  "❌": "croix non faux erreur",
  "❎": "croix carre",
  "➕": "plus ajouter",
  "➖": "moins retirer",
  "➗": "division",
  "✖️": "multiplication croix",
  "🟰": "egal",
  "⚠️": "attention avertissement",
  "🚫": "interdit",
  "❓": "question interrogation",
  "❔": "question blanc",
  "❗": "exclamation important",
  "❕": "exclamation blanc",
  "‼️": "double exclamation",
  "⁉️": "exclamation question",
  "💤": "dort sommeil zzz",
  "💢": "colere veine",
  "💥": "explosion boom",
  "💦": "gouttes sueur",
  "💨": "vent rapide fuite",
  "🕳️": "trou",
  "💬": "bulle message",
  "💭": "bulle pensee",
  "🗯️": "bulle colere",
  "♻️": "recyclage",
  "🔔": "cloche notification",
  "🔕": "cloche muet",
  "🔊": "son haut parleur",
  "🔇": "muet son coupe",
  "📢": "annonce megaphone",
  "➡️": "fleche droite suivant",
  "⬅️": "fleche gauche",
  "⬆️": "fleche haut",
  "⬇️": "fleche bas",
  "🔄": "actualiser boucle",
  "🔝": "top haut",
  "🆕": "nouveau new",
  "🆗": "ok accord",
  "🆒": "cool",
  "👑": "couronne roi meilleur",
  "💎": "diamant precieux",
  "🏁": "arrivee damier",
};
