//! The engine's discovery document: which formats it opens, in which modes, and at which address.
//!
//! Euro-Office (like any WOPI client) publishes it at `/hosting/discovery`. The XML is generated by
//! the engine and regular, so it is read with a small attribute scanner rather than a parser
//! dependency: every `<action name ext urlsrc [targetext]>` is kept, the first one of a kind wins.

use std::collections::HashMap;
use std::fmt::Write as _;

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use super::error::OfficeError;

/// How a session opens a file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum Mode {
    Edit,
    View,
    /// Convert a legacy format into a copy, then edit the copy.
    Convert,
}

/// A conversion the engine offers for an extension.
#[derive(Debug, Clone)]
pub struct Convert {
    pub urlsrc: String,
    pub target_ext: String,
}

/// The actions the engine offers for one extension.
#[derive(Debug, Clone, Default)]
pub struct Actions {
    pub edit: Option<String>,
    pub view: Option<String>,
    pub convert: Option<Convert>,
}

/// The whole discovery, by lower-case extension.
#[derive(Debug, Clone)]
pub struct Discovery {
    by_ext: HashMap<String, Actions>,
}

impl Discovery {
    /// Read a discovery document. Fails when it holds no usable action.
    pub fn parse(xml: &str) -> Result<Self, OfficeError> {
        let mut by_ext: HashMap<String, Actions> = HashMap::new();
        let mut rest = xml;
        while let Some(start) = rest.find("<action ") {
            let after = &rest[start + "<action ".len()..];
            let end = after
                .find('>')
                .ok_or(OfficeError::Discovery("unterminated action"))?;
            let attrs = attributes(&after[..end]);
            rest = &after[end..];
            let (Some(name), Some(ext), Some(urlsrc)) =
                (attrs.get("name"), attrs.get("ext"), attrs.get("urlsrc"))
            else {
                continue;
            };
            let entry = by_ext.entry(ext.to_ascii_lowercase()).or_default();
            match name.as_str() {
                "edit" => {
                    entry.edit.get_or_insert_with(|| urlsrc.clone());
                }
                "view" => {
                    entry.view.get_or_insert_with(|| urlsrc.clone());
                }
                "convert" => {
                    if let Some(target) = attrs.get("targetext") {
                        entry.convert.get_or_insert_with(|| Convert {
                            urlsrc: urlsrc.clone(),
                            target_ext: target.to_ascii_lowercase(),
                        });
                    }
                }
                _ => {}
            }
        }
        by_ext.retain(|_, a| a.edit.is_some() || a.view.is_some() || a.convert.is_some());
        if by_ext.is_empty() {
            return Err(OfficeError::Discovery("no action"));
        }
        Ok(Self { by_ext })
    }

    pub fn actions(&self, ext: &str) -> Option<&Actions> {
        self.by_ext.get(&ext.to_ascii_lowercase())
    }

    /// Extensions the engine edits in place.
    pub fn editable(&self) -> Vec<String> {
        self.collect(|a| a.edit.is_some())
    }

    /// Extensions the engine only shows (no edit, no conversion).
    pub fn viewable(&self) -> Vec<String> {
        self.collect(|a| a.edit.is_none() && a.convert.is_none() && a.view.is_some())
    }

    /// Extensions the engine converts into an editable copy.
    pub fn convertible(&self) -> Vec<String> {
        self.collect(|a| a.edit.is_none() && a.convert.is_some())
    }

    fn collect(&self, keep: impl Fn(&Actions) -> bool) -> Vec<String> {
        let mut out: Vec<String> = self
            .by_ext
            .iter()
            .filter(|(_, a)| keep(a))
            .map(|(e, _)| e.clone())
            .collect();
        out.sort();
        out
    }

    /// The address that opens `ext` in `mode` for the file at `wopi_src`, in `lang` (an engine
    /// language tag such as `fr-FR`). `None` when the engine has no such action.
    pub fn action_url(&self, ext: &str, mode: Mode, wopi_src: &str, lang: &str) -> Option<String> {
        let actions = self.actions(ext)?;
        let urlsrc = match mode {
            Mode::Edit => actions.edit.as_ref()?,
            Mode::View => actions.view.as_ref().or(actions.edit.as_ref())?,
            Mode::Convert => &actions.convert.as_ref()?.urlsrc,
        };
        Some(fill(urlsrc, wopi_src, lang))
    }
}

/// Fill a discovery address: the language placeholders take `lang`, every other optional
/// placeholder is dropped, and the file's WOPI address is appended.
fn fill(urlsrc: &str, wopi_src: &str, lang: &str) -> String {
    let mut out = String::with_capacity(urlsrc.len() + wopi_src.len());
    let mut rest = urlsrc;
    while let Some(open) = rest.find('<') {
        out.push_str(&rest[..open]);
        let Some(close) = rest[open..].find('>') else {
            break;
        };
        let inner = &rest[open + 1..open + close];
        if inner.contains("UI_LLCC") || inner.contains("DC_LLCC") {
            out.push_str(&inner.replace("UI_LLCC", lang).replace("DC_LLCC", lang));
        }
        rest = &rest[open + close + 1..];
    }
    out.push_str(rest);
    while out.contains("&&") {
        out = out.replace("&&", "&");
    }
    out = out.replace("?&", "?");
    let joiner = if out.ends_with('?') || out.ends_with('&') {
        ""
    } else if out.contains('?') {
        "&"
    } else {
        "?"
    };
    format!("{out}{joiner}WOPISrc={}", encode(wopi_src))
}

/// Percent-encode a query value.
fn encode(value: &str) -> String {
    let mut out = String::with_capacity(value.len() * 3);
    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            _ => {
                let _ = write!(out, "%{byte:02X}");
            }
        }
    }
    out
}

/// The `key="value"` pairs of a tag, entities decoded.
fn attributes(raw: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();
    let mut rest = raw;
    while let Some(eq) = rest.find("=\"") {
        let name = rest[..eq]
            .trim()
            .rsplit(char::is_whitespace)
            .next()
            .unwrap_or("")
            .to_owned();
        let value_start = eq + 2;
        let Some(len) = rest[value_start..].find('"') else {
            break;
        };
        out.insert(name, unescape(&rest[value_start..value_start + len]));
        rest = &rest[value_start + len + 1..];
    }
    out
}

fn unescape(value: &str) -> String {
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

#[cfg(test)]
mod tests {
    use super::*;

    const XML: &str = include_str!("testdata/euro-office-9.3.4-discovery.xml");

    #[test]
    fn the_engine_document_lists_what_it_edits_converts_and_shows() {
        let discovery = Discovery::parse(XML).expect("parse");
        let edit = discovery.editable();
        for ext in ["docx", "xlsx", "pptx", "odt", "ods", "odp", "csv", "pdf"] {
            assert!(edit.contains(&ext.to_owned()), "{ext} is editable");
        }
        let convert = discovery.convertible();
        for ext in ["doc", "xls", "ppt", "pages", "numbers", "key"] {
            assert!(convert.contains(&ext.to_owned()), "{ext} is convertible");
        }
        assert_eq!(
            discovery
                .actions("doc")
                .and_then(|a| a.convert.as_ref())
                .map(|c| c.target_ext.as_str()),
            Some("docx")
        );
        assert!(discovery.viewable().contains(&"vsdx".to_owned()));
        assert!(
            !discovery.viewable().contains(&"docx".to_owned()),
            "an editable format is not listed as view-only"
        );
    }

    #[test]
    fn an_address_fills_the_language_and_drops_the_other_options() {
        let discovery = Discovery::parse(XML).expect("parse");
        let url = discovery
            .action_url(
                "docx",
                Mode::Edit,
                "http://api:8081/wopi/files/abc",
                "fr-FR",
            )
            .expect("docx edit");
        assert_eq!(
            url,
            "https://office.example.org/hosting/wopi/word/edit?rs=fr-FR&ui=fr-FR&WOPISrc=http%3A%2F%2Fapi%3A8081%2Fwopi%2Ffiles%2Fabc"
        );
        let view = discovery
            .action_url(
                "vsdx",
                Mode::View,
                "http://api:8081/wopi/files/abc",
                "pl-PL",
            )
            .expect("vsdx view");
        assert!(view.starts_with("https://office.example.org/hosting/wopi/diagram/view?"));
        assert!(discovery
            .action_url("vsdx", Mode::Edit, "x", "fr-FR")
            .is_none());
        assert!(discovery
            .action_url("exe", Mode::View, "x", "fr-FR")
            .is_none());
    }

    #[test]
    fn a_document_without_actions_is_refused() {
        assert!(Discovery::parse("<wopi-discovery></wopi-discovery>").is_err());
    }

    #[test]
    fn entities_in_an_address_are_decoded() {
        let xml = r#"<action name="edit" ext="docx" urlsrc="https://o.test/e?&lt;ui=UI_LLCC&amp;&gt;&amp;a=1"/>"#;
        let discovery = Discovery::parse(xml).expect("parse");
        assert_eq!(
            discovery
                .action_url("docx", Mode::Edit, "w", "de-DE")
                .as_deref(),
            Some("https://o.test/e?ui=de-DE&a=1&WOPISrc=w")
        );
    }
}
